### PR TITLE
Update Case Study Video Images

### PR DESCRIPTION
**Pull request by ksatx**
Update Images on Video Case Studies so they're more easily identifiable as videos

### CODE REVIEW

**Comment by ksatx** [comment]
@paulatulis not totally sure where to use Cloudinary in my workflow so I might need you to help me out tomorrow.

**Comment by ksatx** [comment]
[Update Video Case Study Images So User Easily Knows That They Are Videos](https://trello.com/c/A2XzQDKc/290-update-video-case-study-images-so-user-easily-knows-that-they-are-videos)

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit f219aecc5f440b9ab5cfc8750b7956a99087609e

https://deploy-preview-1281--stoplightio.netlify.com

**Comment by paulatulis** [comment]
@ksatx sounds good! Cloudinary should pop up when you're in admin and are trying to add media to a page. It looks like here you made changes directly to the code, so you may not need to worry about anything Cloudinary related. If the intent was to add via Netlify admin and Cloudinary wasn't showing up or functioning properly, let's definitely take a look.

**Pull request merged**
