### PR TITLE
feat: WIP new home page layout & sections

### PR DESCRIPTION
**Pull request by paulatulis**
Starting to re-organize home page. 
- Removed two product cards from Hero and replaced with one CTA button. Not married to this, but need to confirm the most important thing someone should see as soon as they land on the home page.
- Added six cards based on https://docs.google.com/document/d/1hQYjJR0rCjSRqfQxT4u5eXlv6j-uWus6mbo-rOqW5ws/edit#heading=h.f3hlossidk0
- Bumped case studies down, removed Testimonials and replaced with the SEO features at the bottom. 
- Replaced chips with border-b line since people get confused and try to click on chips
- Updated section titles to be consistent with how they look on the rest of the landing pages

Let me know initial thoughts!

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 1416798598922ea7a9326897c380ad15e7439d90

https://deploy-preview-1431--stoplightio.netlify.com

**Comment by paulatulis** [comment]
Currently, it looks very sparse up top.  I think the two product cards looked really good in comparison, so I would like to explore adding them back and changing the content to match what we want to drive people toward, until we have resources to create custom graphics. 

Screen Shot 2020-03-12 at 3 08 58 PM

Here's what it would look like if we made the CTA button larger and moved the cards up into the hero, but it still isn't very interesting. 
Screen Shot 2020-03-12 at 3 08 30 PM

Here's an example of homepage hero with custom graphic
Screen Shot 2020-03-12 at 3 11 00 PM

I tried doing something similar with Stoplight Dude, but it did not look great. However, if we like Stoplight Dude and want to go in this direction, I will spend more time on it, so just let me know.

**Comment by paulatulis** [comment]
[Re-configure Home Page](https://trello.com/c/8Yg2mM9U/419-re-configure-home-page)

**Comment by falsaffa** [comment]
Damn, its looking much better than what we have now.

I wouldn't worry too much about the gap, we will be putting a graphic to fill the space up (as far as I understand).

Only criticism is on the content. The paragraphs are too long and we need to shave them down to ~4 lines so that it doesn't look as dense. (What do you think @paulatulis and @ksatx ?)

**Comment by paulatulis** [comment]
> I wouldn't worry too much about the gap, we will be putting a graphic to fill the space up (as far as I understand).

I feel like this might take longer than we expect, so maybe we get it to a good place sans graphic in case.

> Only criticism is on the content. The paragraphs are too long and we need to shave them down to ~4 lines so that it doesn't look as dense. (What do you think @paulatulis and @ksatx ?)

I agree. I think it's a little text-heavy. Will go through and cut down.

**Comment by ksatx** [comment]
😭😭😭😭 I closed the tab with all my comments drafted in it and now I have to write them again

**Comment by ksatx** [comment]
Initial Thoughts
- Bringing back the curved hero could cut down on the spartan look a bit
- H2 looks short given the amount of space. Adding another sentence brings balance and allows for a little more keyword stuffing. I tried "Streamline your API Development workflow with a powerful API creation platform. Transform the way your team designs, documents, and mocks APIs."
- A longer CTA, larger font, additional padding also fills the Hero out more, without being too cluttered. I realize this breaks on other pages, but I think the homepage is the one place that deserves some custom components.
- Based on the a/b testing that Salt did last year, the main purple color has a better click rate. Let's use Dark Violet (#BB27DD) for now, but leave the hover color green, and post-launch we use Google Optimize to test.

> > Only criticism is on the content. The paragraphs are too long and we need to shave them down to ~4 lines so that it doesn't look as dense. (What do you think @paulatulis and @ksatx ?)
> 
> I agree. I think it's a little text-heavy. Will go through and cut down.

I also agree on the text, let's shave it down. The case-studies cards might be a good place to draw inspiration.  Super rough mock-up, but essentially replacing the logos with font-awesome iconography (especially the ones used in platform), adding a title, and then updating tags. 

image



Copying this in here to keep conversation together, I think playing with this Tailwind layout might be another good approach, subbing the video for a top-notch gif or gif-a-like, and changing the email form into a get started CTA.

image

**Comment by ksatx** [comment]
I added iconography to this "what style is in the wild" sheet. They're not all 100% accurate but at least they're representative.  I have a hard time tracking down which icons are being used in the code. https://docs.google.com/presentation/d/1pTAUUT61yNkQXaUvIpssfyudjEfNDgN4oGFvlCwz2Pg/edit?usp=sharing

**Comment by paulatulis** [comment]
1. Made Hero look more similar to the example from tailwind with left and right content
2. Updated cards and skimmed down on text length

@ksatx if you want to hop on a call together to go over some of the small details, let me know. It looked odd with both icons at the top of the card and those tags at the bottom. Too much going on.

Still need to decide on a video/gif and finalize copy/cta hrefs

Screen Shot 2020-03-17 at 3 56 01 PM

**Comment by ksatx** [comment]
Ba da ba ba ba, I'm loving it.

I do think we need some kind of something at the bottom border of the hero, but the curved hero would be too much with the particles animation and gif/video. I'm lacking inspiration on how to soften that break up a little. Marc might have some ideas, but it's ultimately a minor detail. 

> Still need to decide on a video/gif

@falsaffa any chance you could record a really great high-level capture that we can turn into a gif, a la [Sketch](https://www.sketch.com/)? Not quite like their main video, but something along the lines of the videos they use in those three cards below the main video? (Sorry, did not capture this section in the recording below) We've got a smaller space to work with so we want to make sure it's effective given the size. 

@paulatulis what do you think about the way their cards fly in on scroll?

fly-in-cards

> It looked odd with both icons at the top of the card and those tags at the bottom. Too much going on.

Agreed, looks good without.

The yellow tag is hard to read, so in the absence of a real sixth color, I tried the lavender used in platform - it ends up being a lot of purple in the bottom row, so we might try moving around colors, but I think it's better than the yellow. 

.text-yellow -> #44337a
.border-yellow-lighter -> #9f7aea
.bg-yellow-lightest -> #e9d8fd

image

**Comment by paulatulis** [comment]
Closing because everything is in https://github.com/stoplightio/stoplight.io/pull/1436

**Pull request closed without merging**
