### PR TITLE
Update studio-launch.md

### PR DESCRIPTION
**Pull request by ksatx**
Update hero image

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 0bb8de7e2bb4bf1cb6e193ad8ebd70807a45e97f

https://deploy-preview-1282--stoplightio.netlify.com

**Comment by ksatx** [comment]
Responding to this tweet - [https://twitter.com/TomCaflisch/status/1202976262232432645](https://twitter.com/TomCaflisch/status/1202976262232432645)

**Comment by lottamus** [comment]
Still not _super_ easy to read but that's more of a design issue on our end 🤷‍♂ . Maybe just use a textured image?

image

**Comment by ksatx** [comment]
Better? 

image

**Pull request merged**
