### PR TITLE
chore: move collage to bottom, center subfeatures

### PR DESCRIPTION
**Pull request by paulatulis**
Per Dave's feedback, moved collage to bottom of page. This made the subfeatures look awkward the way they were aligned so I also updated them to be centered.

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 2c3ee1b2856c6a80e24a571160b05bdd98ff3950

https://deploy-preview-1497--stoplightio.netlify.app

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 1b89ff837c23aea896e1ca7e0c8d6a8fe22c9eab

https://deploy-preview-1497--stoplightio.netlify.app

**Comment by mnaumanali94** [comment]
The centered sections I'm not sure about. Lets keep them left aligned. Also we'd probably want the case study + collage to be same section. Like collage followed by case study. 

We can also just table this tell we have all the feedback from Dave.

**Comment by paulatulis** [comment]
> The centered sections I'm not sure about. Lets keep them left aligned. Also we'd probably want the case study + collage to be same section. Like collage followed by case study.
> 

Moved features back to left aligned and moved collage above case study. Please let me know if there's anything else that needs attention. 

> We can also just table this tell we have all the feedback from Dave.

Sounds good.

**Comment by ksatx** [comment]
For what it's worth, I like the center-aligned features.

**Comment by mnaumanali94** [comment]
Looks good to me! Center aligned is really looked down upon in terms of readability so might as well stay away from it where we can.

**Pull request merged**
