### PR TITLE
responsive home page, #team columns, button spacing

### PR DESCRIPTION
**Pull request by bishopZ**
The homepage #Team section displays in two columns, which were getting crushed on small screens. Changed them to display as two rows on small screens. Also adjusted the spacing of buttons when there is more than one at the bottom of a feature-section.

### CODE REVIEW

**Comment by marbemac** [comment]
Hey dude, thanks for working on this! We are actually implementing a new homepage as I type this (started two days ago). Happy to accept any PRs / polish once we have that code up here!

**Comment by bishopZ** [comment]
Ok. It would have been good to know that earlier this week.

**Comment by bishopZ** [comment]
You are right though. The site could use an update. Looking forward to the new hotness :)

**Comment by marbemac** [comment]
It still maintains the same vibe, and it's not a completely re-write. We are just doing a big update on the existing design - some or all of your PRs might be applicable afterwards!

**Comment by bishopZ** [comment]
this one has conflicts. i will revisit it later. closing for now.

**Pull request closed without merging**
