### PR TITLE
feat: add hero to enterprise page

### PR DESCRIPTION
**Pull request by paulatulis**
#1238 

Want to swap out screenshot of dependency graph if there's a more involved example. @lottamus let me know if you found one or where I can dig more. 

Also is it weird if it's not in dark mode? I think if it were, it would look too dark against the background of the enterprise landing page, but it's not consistent with the others product landing pages. 

Screenshot 2019-11-12 at 1 24 17 PM

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 3b6cb33bdbce0715ff1f0770835c2a13856b40df

https://deploy-preview-1244--stoplightio.netlify.com

**Comment by ssspear** [comment]
> Also is it weird if it's not in dark mode?

Not weird at all. I think you're right about the page being too dark. I also can probably get you a better dependency graph. I'll see what I have

**Comment by paulatulis** [comment]
> Is there a way to remove this drop shadow? It's not consistent with the other landing pages. Example below:
> 
> Screen Shot 2019-11-12 at 1 35 00 PM
> 
> Screen Shot 2019-11-12 at 1 35 22 PM

@ssspear agreed! Let me know if you have a moment to go over options for this. On other pages, the shadow is hidden by a feature bar (ex. https://stoplight.io/studio/) and that has anchor links to different parts of the page. Since the Enterprise page is a little different, I'm not sure what we'd link to if I were to put in a feature bar. Just removing the shadow also looks weird. Trying to think about how we can make a divider without overcomplicating it.

**Comment by ksatx** [comment]
[get dependency graph on https://stoplight.io/enterprise/](https://trello.com/c/fFcjp3Jw/246-get-dependency-graph-on-https-stoplightio-enterprise)

**Comment by paulatulis** [comment]
Added new [Hero](https://github.com/stoplightio/stoplight.io/pull/1244/commits/c52058f957881fa2eb2ad2404cf62f350833d08d) - thank you @lottamus for the screenshot and for changing shadow.



Screenshot 2019-11-13 at 6 09 32 PM

**Pull request merged**
