### PR TITLE
add platform CTA to spectral page

### PR DESCRIPTION
**Pull request by texas-kristen**

### CODE REVIEW

**Comment by texas-kristen** [comment]
@paulatulis yeah, that makes sense. I'm not totally sure where to add more context. This page is a major leak in the acquisition funnel imo since the 'baked in' message is the very last feature section. What about something like this?

image

**Comment by texas-kristen** [comment]
@paulatulis I just realized I didn't actually commit the changes in that screenshot, which way are you saying is fine for now?

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 09a840020d613c06f170c3363447185d0ca7abc3

https://deploy-preview-1563--stoplightio.netlify.app

**Comment by paulatulis** [comment]
> @paulatulis I just realized I didn't actually commit the changes in that screenshot, which way are you saying is fine for now?

Whoops! Sorry I was vague! Either or, honestly. I don't know if one is more clear than the other ('Start Linting' vs 'Use Spectral' ) since both say 'In Stoplight' which is what would be confusing for someone clicking through IMO. I will give hand over artistic direction to you and we can noodle more on it if/when we A/B test - is that okay?

**Pull request merged**
