### PR TITLE
fix: do not make api call in enterprise submit

### PR DESCRIPTION
**Pull request by paulatulis**
Related to: [Hubspot doesn't recognize form submissions as being from the same contact #1383
](https://github.com/stoplightio/stoplight.io/issues/1383)

I didn't completely delete any code because I'm not sure if this is the best way forward, but if we don't want a contact record made twice, we don't need to make a POST call to the HubSpot API when someone clicks the Book a Demo button on the Enterprise page. The button on the Enterprise page should just be a link that saves the email address entered and then passes the email on to the actual form. 

Instead of making an axios call in the `useSubmitEmailForm` hook, I set the new `window.location.href` to that of the link with utm params so that it's capturing that data for GA but not sending anything to be recorded by HubSpot. 

Let me know if this makes sense and seems like a good solution. We are not using this hook anywhere else in the code, so I don't think it should have an affect on any other forms, but would love someone else to review and give their opinion.

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 3fc1c32a257d83793a2343e19f91c7dfcfab9d8d

https://deploy-preview-1385--stoplightio.netlify.com

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 31727b4c256942a15e817b1efab2f6bad6c5da38

https://deploy-preview-1385--stoplightio.netlify.com

**Comment by ksatx** [comment]
I'm honestly not sure on this one, I'll defer to @falsaffa

**Comment by paulatulis** [comment]
I'm closing this because we actually do want to record both forms submitting. If someone fills in their email on the enterprise page and then doesn't submit the demo form on the demo form page, we want to still record that initial email. 

Looking into how to fix logic in HubSpot/Salesforce instead of in the code base.

**Pull request closed without merging**
