### PR TITLE
Testing Inline Widget

### PR DESCRIPTION
**Pull request by ksatx**
Testing embedded sign-up widget on blog

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 34a79c614b53dcd678f0f92be5a2780b109ef151

https://deploy-preview-1303--stoplightio.netlify.com

**Comment by ksatx** [comment]
@paulatulis I'm testing out some inline widgets for the blog. It's not showing up on the preview, do I have to put it inside of an iframe?

**Comment by ksatx** [comment]
[In-line Forms](https://trello.com/c/U4uP43MN/323-in-line-forms)

**Comment by paulatulis** [comment]
Looking into this. I added the script to index.js with no luck. 

<script id="convertful-api" src="https://app.convertful.com/Convertful.js?owner=4983" async />

If there's a way I can log into Convertful to see the documentation, I might be able to access some additional troubleshooting info, so let me know.

**Pull request merged**
