### PR TITLE
update footer

### PR DESCRIPTION
**Pull request by ksatx**
update foot for SEO internal linking

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 7e3b8121a1f9d4d6f4a715474cb9163e9b4aaf3c

https://deploy-preview-1301--stoplightio.netlify.com

**Comment by ksatx** [comment]
Added 'Composite APIs' subpage

**Comment by ksatx** [comment]
[SEO API Types Interlinking](https://trello.com/c/CuiICoKV/316-seo-api-types-interlinking)

**Comment by paulatulis** [comment]
Looks like the related article cards are supposed to take in the hero image, so because these don't have an image, it's just pulling in the color.

**Comment by ksatx** [comment]
@ssspear ditto what Paula said. Since these are for SEO, not on the blog or anything, I figured blue was a safe bet. @paulatulis I don't know if card images vs hero images are on the components list off the top of my head, but sometimes we run into stuff like this where a good card image is a really crappy hero image and vice versa 
image

**Pull request merged**
