### PR TITLE
remove 404 internal links

### PR DESCRIPTION
**Pull request by ksatx**
Assignment from Callum. Removed dead & dated link, not sure what I need to change in \public\_redirects. @paulatulis how does that file fit into the site architecture? 

> Hey Kristen,
> Just working my way through the monthly technical health checks for the site.
> Can we get the below pages redirected to the most relevant alternative page or if not possible then the homepage will suffice.
> 
> https://stoplight.io/blog/changelog/
> https://stoplight.io/platform/scenarios/
> https://stoplight.io/testing/
> https://stoplight.io/testing/enterprise/
> 
> Thanks,
> Callum

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit c9e95e29056a2dfdb6e3322ab0d67577088fc438

https://deploy-preview-1444--stoplightio.netlify.com

**Comment by paulatulis** [comment]
@ksatx the redirects file probably also needs to be updated based on the recommendations.

For example if you look at this section: 

Screen Shot 2020-04-13 at 3 20 25 PM


going to stoplight.io/login will take you to https://next.stoplight.io/login
going to stoplight.io/join will take you to https://next.stoplight.io/join
...and so on


for this section 
Screen Shot 2020-04-13 at 3 20 33 PM


going to stoplight.io/platform/prism will redirect to https://stoplight.io/mocking/
...and so on


So for example, changing https://stoplight.io/blog/changelog/ to redirect home would look like: 

`/blog/changelog /
`

I feel like you would know best if
https://stoplight.io/blog/changelog/
https://stoplight.io/platform/scenarios/
https://stoplight.io/testing/
https://stoplight.io/testing/enterprise/
should update to a new redirect or if we should just change them to the homepage, but let me know if you need help or I can clarify more (or if the above did not answer your question)!

**Comment by ksatx** [comment]
@paulatulis that part makes sense, I just don't quite understand how that file is referenced in other places because the files type literally just shows up as "File" for me. I wasn't sure if it actually did something, or if it was more like comments/docs. 

Going to plugin updates and commit momentarily, will re-request review.

**Comment by paulatulis** [comment]
> @paulatulis that part makes sense, I just don't quite understand how that file is referenced in other places because the files type literally just shows up as "File" for me. I wasn't sure if it actually did something, or if it was more like comments/docs.
> 
> Going to plugin updates and commit momentarily, will re-request review.

**Comment by paulatulis** [comment]
> @paulatulis that part makes sense, I just don't quite understand how that file is referenced in other places because the files type literally just shows up as "File" for me. I wasn't sure if it actually did something, or if it was more like comments/docs.
> 
> Going to plugin updates and commit momentarily, will re-request review.

Ah okay! Yes, that's how you do it with Netlify. See https://docs.netlify.com/routing/redirects/ for more info

**Pull request merged**
