### PR TITLE
Blog post and new pages

### PR DESCRIPTION
**Pull request by tbarn**

### CODE REVIEW

**Comment by tbarn** [comment]
Just noticed webinars doesn't have an icon.

**Comment by tbarn** [comment]
Merged #793 first.

**Comment by rowa97** [comment]
Gartner Cool Vendor is still not ready to be pushed

**Comment by lottamus** [comment]
> Gartner Cool Vendor is still not ready to be pushed

It's hidden

**Comment by tbarn** [comment]
@lottamus looks good to me.

**Pull request merged**
