### PR TITLE
chore: cta based on path

### PR DESCRIPTION
**Pull request by paulatulis**
Since 'Start Designing for Free' was doing well in our A/B test for the 'Get Started' CTA, I thought it might be interesting to customize the CTA based on the landing page. Only did a few that sound most natural (For example, 'Start Governing for Free' sounds awkward, so did not make a custom one for /api-governance), but if you have any ideas for others, feel free to add.

### CODE REVIEW

**Comment by mnaumanali94** [comment]
Love this! Think we also change the CTA in the hero?

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit be7d4a0ae8b9905d1760952bb96fa6f46266347e

https://deploy-preview-1735--stoplightio.netlify.app

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 3306425ea8a14c3500f75d60ef4146374585b699

https://deploy-preview-1735--stoplightio.netlify.app

**Comment by paulatulis** [comment]
> Love this! Think we also change the CTA in the hero?

Yes, great idea. Just added those as well.

**Comment by mnaumanali94** [comment]
Nice! Looks good. One last thing. Are we supposed to have `Start designing for free` everywhere else or are we sticking to get started for free?

**Comment by paulatulis** [comment]
> Nice! Looks good. One last thing. Are we supposed to have `Start designing for free` everywhere else or are we sticking to get started for free?

I was going back and forth on that. I don't know if Start Designing for Free as a default makes sense on every single page...but it did win the test. What do you think? Maybe we can chat quickly about it in the sync tomorrow?

**Comment by mnaumanali94** [comment]
That sounds good. Meanwhile we can merge this.

**Review by mnaumanali94 — APPROVED** [review]

**Pull request merged**
