### PR TITLE
Adds preview to design checklist form

### PR DESCRIPTION
**Pull request by mnaumanali94**

### CODE REVIEW

**Comment by lottamus** [comment]
:heavy_check_mark: Deploy preview for *stoplightio* ready!


:hammer: Explore the source changes: d8aac8ca5fd9db97a65ee1ff078ef630ae7ebf73

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/stoplightio/deploys/5feae2ec80b29f00074c709d](https://app.netlify.com/sites/stoplightio/deploys/5feae2ec80b29f00074c709d?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-1697--stoplightio.netlify.app](https://deploy-preview-1697--stoplightio.netlify.app?utm_source=github&utm_campaign=bot_dp)

**Review by paulatulis — CHANGES_REQUESTED** [review]
Looks good! Hero image has typo and it is a little off on a small screen (for me at least)


Screen Shot 2020-12-29 at 8 59 32 AM

**Comment by paulatulis** [comment]
It still says Essentials but I think everything else looks nice!

Screen Shot 2020-12-29 at 10 13 07 AM

**Comment by mnaumanali94** [comment]
That's a caching problem 🤦‍♂️

I don't think its worth it to change the name to fix that. What do you think?

Anybody looking at it the first time would see the right thing

long-cta-button 3-4

**Comment by paulatulis** [comment]
Ah okay! All set then.

**Review by paulatulis — APPROVED** [review]

**Pull request merged**
