### PR TITLE
Adds design-checklist CTA to API types

### PR DESCRIPTION
**Pull request by mnaumanali94**

### CODE REVIEW

**Comment by lottamus** [comment]
:heavy_check_mark: Deploy preview for *stoplightio* ready!


:hammer: Explore the source changes: 3bc736b913c31b2f60b50f47027380b9b8b2cd8f

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/stoplightio/deploys/5fe3c25199e8db00073e5003](https://app.netlify.com/sites/stoplightio/deploys/5fe3c25199e8db00073e5003?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-1695--stoplightio.netlify.app](https://deploy-preview-1695--stoplightio.netlify.app?utm_source=github&utm_campaign=bot_dp)

**Comment by lottamus** [comment]
:heavy_check_mark: Deploy preview for *stoplightio* ready!


:hammer: Explore the source changes: ff19a410b0fdf964d0b35165bff0683121bb7007

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/stoplightio/deploys/5fe3c2599a90e500078b5d2d](https://app.netlify.com/sites/stoplightio/deploys/5fe3c2599a90e500078b5d2d?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-1695--stoplightio.netlify.app](https://deploy-preview-1695--stoplightio.netlify.app?utm_source=github&utm_campaign=bot_dp)

**Comment by lottamus** [comment]
:heavy_check_mark: Deploy preview for *stoplightio* ready!


:hammer: Explore the source changes: 5330e07f47be27f677a4ed0e644ee5d34480871e

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/stoplightio/deploys/5fe3c4325f36e00008be8e76](https://app.netlify.com/sites/stoplightio/deploys/5fe3c4325f36e00008be8e76?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-1695--stoplightio.netlify.app](https://deploy-preview-1695--stoplightio.netlify.app?utm_source=github&utm_campaign=bot_dp)

**Review by paulatulis — CHANGES_REQUESTED** [review]
I am so so sorry but just realized this: the CTA image says Essentials and not Essential. Also is the Download Now centered vertically inside the button? Looks the slightest bit closer to the bottom.

**Comment by mnaumanali94** [comment]
> I am so so sorry but just realized this: the CTA image says Essentials and not Essential. Also is the Download Now centered vertically inside the button? Looks the slightest bit closer to the bottom.

Good catch! On it

**Comment by paulatulis** [comment]
Whoops sucessful => successful then it should be good!

**Comment by mnaumanali94** [comment]
🤦‍♂️ I think I should sleep

**Comment by paulatulis** [comment]
> 🤦‍♂️ I think I should sleep

Hahahaha I think you should sleep too!!!!

For whatever reason, it's not refreshed in the deploy preview I am seeing (also tried in incognito), but if I refresh the page, I can see it briefly flash and it looks good, so going to assume it's fixed and will show up correctly in production. 

Screen Shot 2020-12-23 at 5 13 48 PM

**Review by paulatulis — APPROVED** [review]

**Pull request merged**
