### PR TITLE
Create Blog Post “stoplight-v1-5-0-release”

### PR DESCRIPTION
**Pull request by ksatx**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 6c928c4ec951ee19127e067aff9debc355d240e7

https://deploy-preview-1245--stoplightio.netlify.com

**Comment by ksatx** [comment]
Padding on desktop is a little drastic since https://github.com/stoplightio/stoplight.io/pull/1236 but I'm not too sure what to do about that

blog post padding

**Comment by ssspear** [comment]
> Padding on desktop is a little drastic since #1236

Hmm I thought we only changed mobile but I'll double check on that

**Comment by paulatulis** [comment]
Hopefully the changes I made in #1248 will fix this. Apologies for the oversight!

**Pull request merged**
