### PR TITLE
Test illustrations branch tweaks

### PR DESCRIPTION
**Pull request by marbemac**
- updates tailwind, we were on quite an old version
- removes a couple of debug looking files (accounts for much of the diff). were these needed?
- reverts the increase in font size in some areas - just too big IMHO
- tidies up some of the spacing and sizing on the homepage and some other pages
- optimizes the studio image on the home page
- exploring possibility of referring to new release as Stoplight v5 (one major version higher than our latest NEXT saas release). might very well remove that term, just have it in one spot for right now, still TBD
- updates some of the pricing page items and tooltip copy in response to dave's feedback
- updates site copy from overpass to inter. The primary reason is that inter works well at smaller sizes, and is a variable font (much smaller download size). It's also in use now at Mozilla, Github, and a number of other forward looking tech companies - more at https://rsms.me/inter. This might be controversial, happy to chat about it and go back to Overpass if folks really prefer it! Can still of course use Overpass for our logo font regardless of decision here.

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 287ca16247f37ea5342dc28f55ef496e937f556a

https://deploy-preview-1483--stoplightio.netlify.app

**Comment by marbemac** [comment]
Fair enough I'll add poppins back for the headings.

For the muted subtext, could probably also fix w increased line height. Basically these big bold heading + gigantic blocks of text that are all the same color kind of blend together to me. Another option is using paragraphs for the big blocks of text in the feature sections, or frankly it wouldn't hurt to reduce the amount of text a bit?

Screen Shot 2020-06-23 at 10 31 10 AM

**Comment by marbemac** [comment]
cc @ksatx on the `inter` + `poppins` combo, as I know you spent a bit of time choosing `overpass` for the logo text.

**Comment by mnaumanali94** [comment]
Agreed.  I'll look at other pages for long paragraphs and cutting them down. These SEO pages have content that is solely for that purpose. Looks good.

**Comment by ksatx** [comment]
> cc @ksatx on the `inter` + `poppins` combo, as I know you spent a bit of time choosing `overpass` for the logo text.

This was a good move, Overpass doesn't work well for body text, it was always intended to be for headings. No problem updating logo to Poppins.

**Comment by marbemac** [comment]
👍 over to you guys to merge this whenever - LMK if I can help with anything!

**Pull request merged**
