### PR TITLE
feat: cta download option

### LINKED ISSUE #1047: Download buttons/section needed for landing page
For the Studio landing page, we need some download buttons in a new section. Maybe like we had on the Classic website for Mac, Windows, and Linux. 

If there was not three of them needed, I'd suggest as CTAs up top, but I think it would be good to just use the CTA as a place to have an anchor link down to the download section.

### PR DESCRIPTION
**Pull request by ssspear**
Fixes #1047 
In progress.

### CODE REVIEW

**Comment by tbarn** [comment]
@ssspear can you write an example of how I should add this to a landing page YAML file? does it go in `ctas`?

**Comment by ssspear** [comment]
@tbarn Yes, they will go into CTAs, as I think they are being used in the hero and the hero can accommodate multiple ctas. If that's not true, let me know. It could look potentially like this:

```ctas:
    - name: Download for Mac
      download:
        href: 'https://github.com/stoplightio/studio-internal/releases/download/v1.0.0-beta.7/stoplight-studio-1.0.0-beta.7-mac.zip'
        fileName: download-mac
        color: indigo
    - name: Download for Windows
      download:
        href: 'https://github.com/stoplightio/studio-internal/releases/download/v1.0.0-beta.7/stoplight-studio-1.0.0-beta.7.dmg'
        fileName: download-linux
        color: indigo
    - name: Download for Linux
      download:
        href: 'https://github.com/stoplightio/studio-internal/releases/download/v1.0.0-beta.7/stoplight-studio-setup-1.0.0-beta.7.exe'
        fileName: download-windows
        color: indigo```

**Comment by lottamus** [comment]
@ssspear I think you've got the file names for Windows and Linux mixed up

**Comment by ssspear** [comment]
> @ssspear I think you've got the file names for Windows and Linux mixed up

Whoops good catch @lottamus Updated the comment

**Comment by tbarn** [comment]
When I `yarn start` this branch, I'm getting this error: 
```
ERROR in /Users/taylorbarnett/Stoplight/stoplight.io/src/hooks/useSubmitForm.ts
  Module not found: Error: Can't resolve 'js-cookie' in '/Users/taylorbarnett/Stoplight/stoplight.io/src/hooks'
   @ /Users/taylorbarnett/Stoplight/stoplight.io/src/hooks/useSubmitForm.ts 3:0-32 27:16-23
   @ /Users/taylorbarnett/Stoplight/stoplight.io/src/components/Submit/index.tsx
   @ /Users/taylorbarnett/Stoplight/stoplight.io/src/components/CallToAction/index.tsx
   @ /Users/taylorbarnett/Stoplight/stoplight.io/src/components/GartnerCoolVendor/index.tsx
   @ /Users/taylorbarnett/Stoplight/stoplight.io/src/templates/Home/index.tsx
   @ /Users/taylorbarnett/Stoplight/stoplight.io/artifacts/react-static-templates.js
   @ ../lib/bootstrapTemplates.js
   @ multi react-hot-loader/patch ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js index.js
```

**Comment by tbarn** [comment]
Here's a preview from one landing page: 

Screen Shot 2019-08-06 at 4 31 14 PM

You can definitely have multiple, so that's great. A couple of things though that I am worried about: 
It is at the bottom, which I'm not sure a lot of people will scroll down to, even with using an anchor link. 

It would be great if we could bring it up higher in the page so people see it sooner while scrolling, like here: 

Image 2019-08-06 at 4 32 47 PM

I think this will help improve downloads. Also, we won't lose the bottom CTA so we can still use it for other things.

**Comment by tbarn** [comment]
Screen Shot 2019-08-06 at 5 07 11 PM

Looks great in the hero! Icons will make it 🔥.

**Comment by ssspear** [comment]
🔥🔥🔥

Screen Shot 2019-08-06 at 5 14 50 PM

Just use `icon: ['fab', 'apple']` or `icon: ['fab', 'linux']` or `icon: ['fab', 'windows']` in the yaml files!

**Comment by tbarn** [comment]
Awesome. I think if we stick with it at the top, there's no need for anchor links. That's only needed if it is further down.

**Comment by ssspear** [comment]
Awesome. I'll mark it as ready for review, and should we need anchor tags in the future, we can revisit.

**Pull request merged**
