### PR TITLE
Allow free email providers

### PR DESCRIPTION
**Pull request by mnaumanali94**

### CODE REVIEW

**Review by paulatulis — COMMENTED** [review]
I get it for tier 3 forms, but I do think the demo form still needs to check for this to avoid getting lots of junk requests. Thoughts on making a separate rule for that use case?

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 2125bc89eec4e92317d7b28219beb81feea85c78

https://deploy-preview-1731--stoplightio.netlify.app

**Comment by mnaumanali94** [comment]
Request demo uses native hubspot form and that validates against this anyway. That's a setting in hubspot. I'm thinking we're just using the API for tier-3 ones. Can think of any other?

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 944527ee03cfd2a1a42f1eb1e889db0efbe16269

https://deploy-preview-1731--stoplightio.netlify.app

**Review by paulatulis — APPROVED** [review]
Okie doke! Will be interested to see what happens with submission rates.

**Pull request merged**
