### PR TITLE
enhancement: redesign call to action section (#1010)

### LINKED ISSUE #1010: Redesign our call to action section
Our call to action section could use a refresh. Lets take some inspiration from Segment 

**Ours: https://stoplight.io**
image

**Segment: https://segment.com/**
image

### PR DESCRIPTION
**Pull request by ssspear**
Fixes #1010

### CODE REVIEW

**Comment by philsturgeon** [comment]
We got some conflicts here, let me know when its done and I'll approve. 

Also we've been trying this out for other visual changes elsewhere, could you add some screenshots showing key before and after for a CTA to highlight exactly what this has done?

**Comment by ssspear** [comment]
> could you add some screenshots

Before: 
Screen Shot 2019-08-13 at 4 22 46 PM

After:
Screen Shot 2019-08-13 at 4 31 41 PM

**Comment by ssspear** [comment]
@lottamus Having a few issues with the small screens version. Could you take a look?

**Comment by ssspear** [comment]
Closing this for now.

**Pull request closed without merging**
