### PR TITLE
feat: nav bar changes

### PR DESCRIPTION
**Pull request by paulatulis**
**Updates to header:** 

**CONTEXT**
Based on our meeting last week:
- Products are for people who come to the site knowing what they want
- Solutions are for people who have pain points who don't necessarily know what they need

**Products**:
1. Studio 
2. Explorer/Technical Knowledge Base
3. Documentation
4. Mocking

**Solutions/Use Cases**:
1. API Design - creating an API - studio 
2. API Development (mocking) - open source prism or mocking page 
3. API Mocking
4. API Documentation 
5. API Visibility
6. API Governance - we integrate with git, but not a lot of content on this right now. Calls out explorer, LDAP, SSO
7. API Consistency & Quality & Standardization - one page but which verbiage?
8. API Collaboration  
 --divider--
10.  Case Studies
12. I left in Use Cases after our SEO call, but can move to About if we want

**About**:
1. About Us
2. Help center
3. Forum 
4. Webinars 
5. I also added Careers because I think it's intuitive to have under About, but I can remove if anyone has a differing opinion

———————————————————————————————————————————————

**Action Items for Products:**
- Verbiage for the tags and product descriptions - right now they are placeholders
- Confirm what each product tile title should be 
Screen Shot 2020-03-04 at 4 04 31 PM

**Action items for Solutions and About drop downs:**
- Decide on icons and colors for every single menu item - there are quite a few! I don't have a rhyme or reason to the colors as they are for this preview, just going off of current design, so @ksatx let me know what you think is best
- Decide on paths for every menu item. Some don't exist yet, but if we have existing paths, want to confirm the ones we want to use for a specific solution 
Screen Shot 2020-03-04 at 4 04 40 PM
Screen Shot 2020-03-04 at 4 15 50 PM

**Misc. action item:**
- Figure out why About is showing up twice. Perhaps it has to do with caching, but if anyone catches something I forgot to remove, please flag. 
Screen Shot 2020-03-04 at 4 04 36 PM

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 5aa25ef6dd22aec7b8c65c87f1a921e4655eb0fc

https://deploy-preview-1424--stoplightio.netlify.com

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 292728e56c275727fcdb3091c1e006e72ff26fd4

https://deploy-preview-1424--stoplightio.netlify.com

**Comment by ksatx** [comment]
- Icons and icon colors may change in the near future depending on the Superside project, for the moment they look as good as anything. 
- "API Development" should go to /development - it's not used anywhere else as far as I know
- imo, 'Development' shouldn't just go to mocking information. Looking around the rest of the industry, they get used interchangeably a lot, 'Design' as more of an ideology, 'Development' as the verb. i.e. Design-First Development vs. Code-First Development. 
If 'Solutions' is for people that know their pain but don't know what they need, then this page should answer the question "How does Stoplight help me develop APIs", answer "Stoplight helps you by giving you powerful design, virtualization, standardization, and validation tools to develop your API"  More of a high-level overview of all of Stoplight, but specifically speaking to creators. @falsaffa does that check out with you?

> API Consistency & Quality & Standardization - one page but which verbiage?

- my vote is for quality, based on google trends, and it provides a logical place to talk about the Quality Module in the near future. 

image

**Comment by paulatulis** [comment]
Update: 

- Holding on icons and colors for now.
- Agree with you @ksatx -- updated 'Consistency' to 'Quality'. 
- Updated Development to /development
- Made updates to the header and footer as well (remember to adjust your window size to see the changes here)

**Comment by paulatulis** [comment]
[Update Header and Footer to match new layout](https://trello.com/c/NMlwIhKG/418-update-header-and-footer-to-match-new-layout)

**Comment by ksatx** [comment]
I know I said the icons were good, but I'm noticing now that the ones under "About" are mostly blue/orange variations - let's switch it up a bit to give an extra layer of visual distinction, maybe make careers green. You can use this as a reference! https://docs.google.com/presentation/d/1pTAUUT61yNkQXaUvIpssfyudjEfNDgN4oGFvlCwz2Pg/edit?usp=sharing

Other than that, this looks good to me. Do you want us to approve the PR now, or wait until we have all the missing pieces and it's 100% ready to merge?

**Comment by ksatx** [comment]
Also kudos on figuring out why there were two 'Abouts', I also could not tell for the life of my where the 2nd one was coming from.

**Comment by paulatulis** [comment]
> I know I said the icons were good, but I'm noticing now that the ones under "About" are mostly blue/orange variations - let's switch it up a bit to give an extra layer of visual distinction, maybe make careers green. You can use this as a reference! https://docs.google.com/presentation/d/1pTAUUT61yNkQXaUvIpssfyudjEfNDgN4oGFvlCwz2Pg/edit?usp=sharing
> 
> Other than that, this looks good to me. Do you want us to approve the PR now, or wait until we have all the missing pieces and it's 100% ready to merge?

Yeah I figured we should wait until we have the final icons and colors confirmed. I'll make color updates but we shouldn't approve/merge this until the end or at least after we have all of the new landing pages merged, as the following are currently not actual pages:
/development
/visibility
/governance
/consistency
/collaboration

**Comment by paulatulis** [comment]
> Also kudos on figuring out why there were two 'Abouts', I also could not tell for the life of my where the 2nd one was coming from.

It was accounted for twice (once in aboutMenu and once in nonButtons), so I made an update to this snippet: https://github.com/stoplightio/stoplight.io/pull/1424/files#diff-aba8db2975888a7ce908d125ae2c4883R214-R216

That said, I'm sure there's a cleaner way to accomplish this, so if anyone reviewing has a suggestion, please don't be shy!

**Comment by paulatulis** [comment]
1. Put blog under about - @ksatx do you recall if we decided to actually do this? I am blanking.
2. Open Source initiatives go under products - Done, but need to come up with verbiage. See screenshot below. With Prism included, I didn't want to use 'Mocking' twice, so I put Validation, but open to suggestions! Maybe we can do tags for the top 4 and keep icons for the bottom two? 
3. Icons: - Done
    1. Mocking - use servers (the one currently next to Mocking) 
    2. Development - code 
    3. Visibility - chart network
5. Update two right-hand buttons to ‘Sign in’ and ‘Get Started’ - Which paths are we redirecting to for these two buttons?

Screen Shot 2020-03-09 at 9 10 40 AM

Screen Shot 2020-03-09 at 9 18 50 AM

**Comment by paulatulis** [comment]
**Products:**

1. Consistency in the subtext underneath product name - is it a description of what the product is (‘Beautiful free technical documentation in a single click.’), or is it a command (‘Search, filter, and understand complex API Architecture.’)? Or does it matter?
2. Should all products use tags or should all products use icons or should main four products keep tags and two Open Source products keep icons?
3. Banner buttons:
- Confirm link for ‘Get Started’
- Confirm link for ‘Sign in’
4. Colors & Icons: Decide on specific colors/icons
5. Mobile: Can mobile menu stay as is?
6. Footer: Can footer stay as is?

**Comment by ksatx** [comment]
> Put blog under about - @ksatx do you recall if we decided to actually do this? I am blanking.
>

Yyyyeah, I think we did, but looking at it now that Open-Source is under products, it would be kind of sparse imo. Could be worth doing anyway, gives a narrower range of options so it might drive people more effectively? We don't really want people to go to the blog from the homepage, rather the other way around.

> Open Source initiatives go under products - Done, but need to come up with verbiage. See screenshot below. With Prism included, I didn't want to use 'Mocking' twice, so I put Validation, but open to suggestions! Maybe we can do tags for the top 4 and keep icons for the bottom two?
>

Let's make the tag on Explorer "Visibility" and the tag on Stoplight Mocking "Validation", and go with the icons for the bottom two.

We should sync as a growth team on the value/purpose of the open-source pages. I'm starting to think that they derail visitors from the actions we want them to perform (checking out potentially *paid* product pages) and might be more appropriate under 'About'. Like, yeah, here some info about the neat stuff we've baked in if you're looking for that, but the intended user path should start at Studio or whatever. 

> Update two right-hand buttons to ‘Sign in’ and ‘Get Started’ - Which paths are we redirecting to for these two buttons?
>

As far as I know, we're still waiting on the final word and my guess is there will be some sort of workspaces homepage. For now, let's point 'Get Started' at https://stoplight.io/p/signup and 'Sign In'  to https://stoplight.io/p/studio as adequate placeholders.


> **Products:**
> 
> 1. Consistency in the subtext underneath product name - is it a description of what the product is (‘Beautiful free technical documentation in a single click.’), or is it a command (‘Search, filter, and understand complex API Architecture.’)? Or does it matter?
>

Let go with command. "Create beautiful technical documentation in a single click." and "Easily edit & collaborate on OpenAPI, Markdown, and JSON schema."


> 2. Mobile: Can mobile menu stay as is?
>

Design-wise, yes, but let's try to shuffle list items under the same section that they're in on desktop. 

> 3. Footer: Can footer stay as is?
>

Yes

**Comment by paulatulis** [comment]
1. Moved Blog under About menu (keep in mind, there will be a pricing button on the header after all changes are merged as well)
2. Updated tags and subtitles under product tiles - thinking this might change again before it's final
3. Good point about Open Source! I think it's valid, but putting them under About doesn't seem like the most appropriate and getting rid of them seems a little drastic. Agree we should sync as a team.
4.  Updated button links (sign in, get started) and can update again if need be.
6.  After making mobile adjustments, it actually looks a bit weird. If we have an odd number of menus, it looks like this: 

Screen Shot 2020-03-10 at 3 03 07 PM
and I think it looks better like we have it now:
Screen Shot 2020-03-10 at 3 03 31 PM

Will brainstorm other ways of accomplishing consistent menus.

**Comment by ksatx** [comment]
You're right about the mobile nav, it does look better as is. 
Let's touch on the placement of spectral and prism tomorrow in the growth meeting

**Comment by paulatulis** [comment]
Notes from Growth team sync: 


- sign in/get started should look like slack.com. Highlight 'Get Started'
Here are three options: 

1. all uppercase (this seems aggressive)
Screen Shot 2020-03-11 at 11 37 57 AM

2. all lowercase (like we have now, purple highlight just moved over to the Get Started button)
Screen Shot 2020-03-11 at 11 39 02 AM

3. sign in lowercase, GET STARTED in all caps - most like slack.com
Screen Shot 2020-03-11 at 11 39 33 AM

Screen Shot 2020-03-11 at 11 39 19 AM



- Moved Open Source back into separate menu button
Screen Shot 2020-03-11 at 11 41 54 AM



- Added Pricing button to this branch. I don't think it looks like too many buttons with Pricing and Open Source as separate options.

**Comment by ksatx** [comment]
> 3. sign in lowercase, GET STARTED in all caps - most like slack.com

I agree that caps seems aggressive, my personal preference would be sign in lowercase, **Get Started** in bold, so I thought WWSD (what would Scott do) and looked at other top PLG SaaS/dev tool companies that have figured this out already. Examples below. Let's try the Twilio model of Log In in the banner - it reduces the need for aggressive emphasis on Get Started, but still gives a path to people trying to login 

image


- Zoom's entier header is in all caps, and the sign up button is the only header link styled as a button + the font is a little larger. This was the only other example I saw of all caps begin used, and it makes more sense here given that everything is in caps. 

image


- Shopify, similar to Zoom, "Start free trial" is the only header link with a button styling.  
image

- Definitely my favorite, Twilio actually moves the Log In into the banner vs the header. I think this is a good compromise to address Marc's qualms about having it in the first place

image

- Lastly, I think it's too ambitious for now & conflicts with some of the other homepage styling we've talked about, but Dropbox actually uses a slide-out modal on scroll. More of a neat concept to think about on future pages/iterations, not a suggestion for right now. [https://www.dropbox.com/?_hp=c](https://www.dropbox.com/?_hp=c)

> Added Pricing button to this branch. I don't think it looks like too many buttons with Pricing and Open Source as separate options.

Agreed, doesn't look too crowded in my opinion, let go with this. (can't remember if we already settled on this in the growth meeting)

**Comment by paulatulis** [comment]
Moved 'Log In' to top banner and 'Get Started' in lowercase. We can keep iterating on this if it doesn't accomplish what we want in the way we want it to look!

@ksatx happy to look into a slide out modal but I don't think it's happening when I go to their website. Is there any other example you know of?

Screen Shot 2020-03-17 at 4 30 23 PM

**Comment by ksatx** [comment]
> Moved 'Log In' to top banner and 'Get Started' in lowercase. We can keep iterating on this if it doesn't accomplish what we want in the way we want it to look!

Aww yeah, I think this looks great.


> @ksatx happy to look into a slide-out modal but I don't think it's happening when I go to their website. Is there any other example you know of?

Did a quick recording, maybe I'm using the wrong terminology. I think it would be too busy for the homepage, but it's a neat idea to keep in our back pocket for other pages.


slide-out-dropbox

**Comment by paulatulis** [comment]
closing because we have https://github.com/stoplightio/stoplight.io/pull/1431

**Pull request closed without merging**
