### PR TITLE
feat: New Form Templates

### PR DESCRIPTION
**Pull request by paulatulis**
WIP not ready to be reviewed yet

Setting up three different form template options (to start): 
LeftContent
RightContent
MiddleContent - Not finished

To Do:
- Finish MiddleContent template
- CSS
- Rework testimonials to make them more flexible with css
- Figure out routing and how admin config should work with this

Screenshot 2020-01-09 at 3 29 54 PM

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* failed.

Built with commit e7ef82ee08062593f6fcc877873209671679a9d7

https://app.netlify.com/sites/stoplightio/deploys/5e1e458d8e959500078df2cb

**Comment by ksatx** [comment]
[Update demo page to have more social proof and be more clean](https://trello.com/c/tC8hYojI/117-update-demo-page-to-have-more-social-proof-and-be-more-clean)

**Comment by paulatulis** [comment]
Three different formats with testimonials have been created to do multivariate testing. 

To Do: 
- I'm unsure how to go about displaying them all in the same PR/setting this up in admin. 

Will include screenshots for now: 

Left Content
Screenshot 2020-01-17 at 3 07 13 PM


Right Content
Screenshot 2020-01-17 at 2 58 38 PM

Center content
Screenshot 2020-01-17 at 3 00 11 PM

Would love to hear opinions and ideas on how to make these look better!

**Comment by paulatulis** [comment]
@lottamus please let me know if I should request someone else to review these PRs moving forward

**Comment by paulatulis** [comment]
Added another left content option using HubSpot's demo form as a guide.

Need assistance in organizing this in netlify admin. For now it's okay if we just choose one to go with but would like to have that one chosen and implemented by Wednesday's growth meeting.

Screenshot 2020-01-20 at 11 38 09 AM

**Comment by ksatx** [comment]
I personally like this one, especially if we could make those cards "anything cards" so to speak - that's what the SimpleCards are, right? Then, we could swap out a testimonial for a video/badge/meeting agenda like the examples Tamina provided from
[Dropbox](https://lp.dropboxbusiness.com/Dropbox-Webinar-OnDemand.html )
[Hootsuite](https://hootsuite.com/request-demo)
[Salesforce](https://www.salesforce.com/form/demo/crm-sales-demos/)

And create tests around those swaps.

image

**Comment by paulatulis** [comment]
Option for A/B testing in Netlify admin:

[Split Testing](https://docs.netlify.com/site-deploys/split-testing/#run-a-branch-based-test)
- [More about split testing](https://www.netlify.com/blog/2019/09/11/netlify-pro-tip-using-split-testing-to-power-private-beta-releases/)

**Comment by ksatx** [comment]
Having a hard time reading the file diffs...is the left content contained in cards?
image

**Comment by paulatulis** [comment]
@ksatx in this version it is not. Per my meeting on Monday with Scott, we would like to get the new layout up and running as a first step so that we can start looking at any difference in conversion rate because it's an easy win. The next step after this will be to make it A/B testable so we can swap out copy.

@lottamus this is ready for review. I wasn't able to get the form to be sticky and I believe it may have to do with it being part of the hero, but if that's not the case and/or you have any ideas, please let me know.

Screenshot 2020-01-21 at 3 10 41 PM

**Comment by ksatx** [comment]
So is this layout (or the mirror image) held back by the [SimpleCards PR](https://github.com/stoplightio/stoplight.io/pull/1298)? And with the directive to have something live by Wednesday, that's how we arrived at the current iteration?

The larger issue isn't just layout/copy, but being able to plug-play-test different content aside from plain text. 

I think this is a great start if something new needs to be live by tomorrow, but it doesn't really solve the fundamental issue as I understand it. 

image

**Comment by paulatulis** [comment]
> So is this layout (or the mirror image) held back by the [SimpleCards PR](https://github.com/stoplightio/stoplight.io/pull/1298)? And with the directive to have something live by Wednesday, that's how we arrived at the current iteration?
> 
> The larger issue isn't just layout/copy, but being able to plug-play-test different content aside from plain text.
> 
> I think this is a great start if something new needs to be live by tomorrow, but it doesn't really solve the fundamental issue as I understand it.
> 
> image

Agreed! I think it's worth it to have a discussion about what's the most impactful for the team. Once the SimpleCard is merged in, I will be updating Netlify admin to support you making changes. 

In the meantime, if it's important to go live with new copy, I've made more updates that align the sections more evenly.

**Comment by paulatulis** [comment]
@lottamus I would personally say this is ready for review, but I'll wait to confirm that 100% until after our Growth meeting tomorrow so you don't end up reviewing twice. Thanks for everyone's patience!

**Pull request merged**
