### PR TITLE
add mailchimp script

### PR DESCRIPTION
**Pull request by texas-kristen**

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 0dfb67bc5439a7e6d8b040247f3ae3e713efd245

https://deploy-preview-1589--stoplightio.netlify.app

**Comment by texas-kristen** [comment]
Since the font awesome script was just plopped in there, I just dropped the Mailchimp script in. Let me know if there is a better way to add it.

**Comment by texas-kristen** [comment]
Whoops I broke it

**Comment by paulatulis** [comment]
@texas-kristen Sorry but I am ignorant about what this does - would you be able to add the quickest most basic description for the PR? Thank you!

**Pull request closed without merging**
