### PR TITLE
Mocking landing page update

### PR DESCRIPTION
**Pull request by tbarn**
Rough draft done with images

### CODE REVIEW

**Comment by philsturgeon** [comment]
These are great changes. We need the CTA going somewhere then we can get this approved and ready to go when studio is out.

**Comment by tbarn** [comment]
I don't know what to do for images for "Virtualization" and "Automatic Request Validation." 

One idea I had was to combine the "Virtualization" and "Customization" sections since they both talk about dynamic examples, but then "Automatic Request Validation" still needs an image. Before it was easier because there were more (complicated) parts to mocking, so more to take screenshots of. 😆

**Comment by tbarn** [comment]
@ssspear any idea why the hero CTA is not centered in the build preview? but looks good on when I run it locally.

**Comment by ssspear** [comment]
@tbarn It looks like the issue might be coming from the `w-1/2` style here: https://github.com/stoplightio/stoplight.io/blob/develop/src/components/Hero/index.tsx#L188

I removed it on my local version, and all CTAs still appear to be styled properly. Let's see if that helps the issue on the build?

**Comment by lottamus** [comment]
@ssspear we only add that `w-1/2` if there is more than one cta

```ts
{ctas.map((action, i) => (
  <CallToAction key={i} className={cn("m-3 md:w-full", { 'w-1/2': ctas.length > 1 })} {...action} />
))}
```

**Pull request merged**
