### PR TITLE
Spectral Landing

### PR DESCRIPTION
**Pull request by lottamus**
# DO NOT MERGE

https://deploy-preview-967--stoplightio.netlify.com/spectral/

image

### CODE REVIEW

**Comment by tbarn** [comment]
Okay, looks great, I'm going to pull in Adam's changes to it now because I think it was branched before they were merged. 

And then we have to figure out the image situation....

**Comment by tbarn** [comment]
And also adding it to the "Resources" drop down for now. We can figure out later if there's a better place, but I want to make sure it is linked somewhere.

**Comment by lottamus** [comment]
@P0lip is investigating Spectral failing in the production build

**Comment by marbemac** [comment]
Looks great, nice job on the playground @ssspear!

- Add the github button link at bottom as a CTA somewhere at bottom of landing.
- Increase site container to 1250px
- Tweak image size values a bit as described in #974 
- IF easy (e.g. not using virtualized list), allow for multi line error messages in the spectral results panel. as it is, most issues are obscured. user can hover for like 3 seconds to see the title popup, but not great.

**Comment by tbarn** [comment]
There's a GitHub link at the bottom already, just doesn't have the logo.

**Pull request merged**
