### PR TITLE
Chore: add FAQ schema

### PR DESCRIPTION
**Pull request by paulatulis**
Implements many of the FAQ schema [to dos](https://3.basecamp.com/3986751/buckets/8824800/todolists/2820634239) from SALT. 

More to come, but waiting on reply from SALT, so if you approve, please don't merge in just yet.

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 4cbcd3357e5d004623b146b26bf70528882a3e2f

https://deploy-preview-1620--stoplightio.netlify.app

**Review by texas-kristen — CHANGES_REQUESTED** [review]
The following pages are 404'ing or blank

- /api-documentation-guide/basics/
- /api-design-guide/basics/
- /api-development-guide/
- /microservices-guide/
- /mock-api-guide/basics

This one looks good! /api-documentation-guide/best-practices/ - It appears to be the only one that has a single FAQ question on it. Maybe there is a syntac error with the other ones?

**Comment by paulatulis** [comment]
@texas-kristen my brain was on Friday mode, it appears. Just re-configured the structure so that each page can handle more than one question and answer. All of the pages are rendering in the preview, so if you'd be able to double check on your end, that would be wonderful!

**Review by texas-kristen — APPROVED** [review]
@paulatulis all looks good to me now!

**Pull request merged**
