### PR TITLE
feat: remove hubs from marketing site

### PR DESCRIPTION
**Pull request by paulatulis**
- Removed Enterprise and Hubs cards from product dropdown in header since we are not selling Hubs and there is already an Enterprise option in header. 

- Removed Hubs from footer

- Removed Hubs from mobile products header section 

- Removed buttons on /docs and /documentation that redirect to Hubs landing page

Screen Shot 2020-02-12 at 12 31 59 PM

### CODE REVIEW

**Comment by paulatulis** [comment]
[Remove Hubs card from product dropdown](https://trello.com/c/qx8j5oKw/360-remove-hubs-card-from-product-dropdown)

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit caba18fbbfe5a1c5baa7bb2d1c1fd66110e4f9b5

https://deploy-preview-1373--stoplightio.netlify.com

**Comment by falsaffa** [comment]
Screenshot_20200212-130925_Firefox

On mobile, Stoplight Enterprise is still under product. Can you try to remove it?

**Comment by paulatulis** [comment]
@falsaffa I left it there on purpose because there's no other link to the enterprise page on mobile. Should I move it? I think there should be some link to enterprise and it doesn't make this menu look incongruent like it would if we left enterprise on desktop.

**Comment by falsaffa** [comment]
> @falsaffa I left it there on purpose because there's no other link to the enterprise page on mobile. Should I move it? I think there should be some link to enterprise and it doesn't make this menu look incongruent like it would if we left enterprise on desktop.

Oh gotcha. Let's keep it then - I didn't notice it was missing!

**Comment by paulatulis** [comment]
> Before merging, we need to resolve this blog, both the actual wording and the link where it says "Stoplight Hubs" - https://stoplight.io/blog/studio
> 
> "Every API needs documentation, so we created a flexible docs generator from OpenAPI. Though Stoplight Studio supersedes the editor, this documentation product will remain at Stoplight Hubs (as will all of our “next” based tooling) for the foreseeable future. Add your own styles, generate API references, and add additional documentation pages. A consumer’s complete experience of your API includes understanding how it works, what is possible, and how to get started. Hubs help you educate developers, whether external or internal, while ensuring that documentation is automatically updated along with your OpenAPI document."
> 
> **Other things to keep in mind when/if we remove the page altogether**
> 
> We have a couple of inbound links, so we need to put in a redirect in "_redirects" to /docs
> 
> We have a few links that are only going out from /hubs. I haven't looked at them yet but need to place them somewhere else potentially.
> 
> https://stoplight.io/api-documentation-guide/basics/
> https://stoplight.io/documentation/automation/
> https://stoplight.io/documentation/helper/
> https://stoplight.io/documentation/hosted/

@ksatx Thank you for flagging! I'm going to open a new PR to address these items. For now, /hubs is still live, the links to it are just not visible anymore. So if anyone does go to that link, it won't break.

**Pull request merged**
