### PR TITLE
WIP: some updates to feature sections on landing pages

### PR DESCRIPTION
**Pull request by paulatulis**
Just starting to play around with updated product feature layouts 

- Added option to have an overlay to vary the text/image layout
- Made text larger 

changes (please note: these are just placeholder screenshots):
Screen Shot 2020-03-05 at 5 06 59 PM

vs. 

current:
Screen Shot 2020-03-05 at 5 07 06 PM

To do: 
- Figure out how to add gif without slowing down site
- Get approved new text and image content so we can see what this will actually look like

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit 6f16521569131330bdf2f4f345ff9d29c9b73085

https://deploy-preview-1427--stoplightio.netlify.com

**Comment by ksatx** [comment]
Already **_so. much. better._**

**Comment by paulatulis** [comment]
@ksatx added shadow and rounded borders to images. I want to wait until we have the rest of the content finalized to make more changes. I think there will be more adjustments, but let me know if anything jumps out at you in the meantime!

**Comment by paulatulis** [comment]
https://github.com/stoplightio/stoplight.io/pull/1431

**Pull request closed without merging**
