### PR TITLE
chore: clean up Gartner Cool Vendor Form

### PR DESCRIPTION
**Pull request by ksatx**
clean up Gartner form - remove title image because it's massive, remove weird anonymous testimonials

### CODE REVIEW

**Comment by lottamus** [comment]
Deploy preview for *stoplightio* ready!

Built with commit be91fda28cd917b1d8c6ac82aa2241dbbf67c674

https://deploy-preview-1440--stoplightio.netlify.com

**Comment by paulatulis** [comment]
> clean up Gartner form - remove title image because it's massive, remove weird anonymous testimonials

@ksatx really? this is what current website looks like for me with image included - not massive: 
Screen Shot 2020-03-26 at 4 32 11 PM


Can I see what you're seeing? Otherwise, changes look good!

**Comment by ksatx** [comment]
image

**Comment by paulatulis** [comment]
@ksatx apologies for the delay here! I think this has to do with our differing screen sizes. Can you try changing the following in the [ Hero component](https://github.com/stoplightio/stoplight.io/blob/master/src/components/Hero/index.tsx#L206) and see if it makes a difference on your machine?

`{titleImage && (
              <div>
                <Image src={titleImage} className="h-64 md:h-32 sm:hidden" />
              </div>
            )}`

**Comment by ksatx** [comment]
@paulatulis it's not happening anymore, even without changing anything. I feel like it's done this before....randomly started looking normal and then weird again.

**Comment by paulatulis** [comment]
@ksatx what's happening these days when you look at this page?

**Comment by ksatx** [comment]
@paulatulis it looks normal, so I'm going to close this for now

**Pull request closed without merging**
